version: '3.5'

volumes:
  etherpad_postgres_data_vol:
    external: false

services:
  etherpad-postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_DB: etherpad
      POSTGRES_USER: etherpaduser
      POSTGRES_PASSWORD: etherpadpass
    volumes:
      - etherpad_postgres_data_vol:/var/lib/postgresql/data/
    networks:
      - etherpad

  etherpad-proxy:
    image: nginx
    restart: always
    depends_on:
      - etherpad
    volumes:
      - ./images/etherpad/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
      - etherpad

  etherpad:
    build:
      context: ./images/etherpad
    environment:
      DB_HOST: etherpad-postgresql
      DB_NAME: etherpad
      DB_PASS: etherpadpass
      DB_PORT: 5432
      DB_TYPE: postgres
      DB_USER: etherpaduser
      LOGLEVEL: "debug"
      NODE_TLS_REJECT_UNAUTHORIZED: '0'
    volumes:
      - ./images/etherpad/settings.json:/opt/etherpad-lite/settings.json:ro
    depends_on:
      - etherpad-postgresql
    networks:
      - etherpad

  jupyterhub:
    depends_on:
      - etherpad-proxy
    volumes:
      - './images/etherpad/etherpad.token:/opt/etherpad.token:ro'
      - './images/etherpad/jupyterhub_config.py:/jupyterhub_config.d/etherpad.py:ro'

networks:
    etherpad:
        name: etherpad_backend

